In [1]:
import numpy as np
import pandas as pd
from sklearn.model_selection import train_test_split

In [2]:
from sklearn.tree import DecisionTreeClassifier
from sklearn.metrics import confusion_matrix

In [3]:
import sklearn.ensemble as en

In [4]:
from scipy.stats import itemfreq

In [5]:
i=pd.read_csv("iris.csv")

In [6]:
i.shape

(150, 6)

In [14]:
i=i.drop(['Unnamed: 0'], axis=1)

In [46]:
i.head()

Sepal.Length  Sepal.Width  Petal.Length  Petal.Width Species
0           5.1          3.5           1.4          0.2  setosa
1           4.9          3.0           1.4          0.2  setosa
2           4.7          3.2           1.3          0.2  setosa
3           4.6          3.1           1.5          0.2  setosa
4           5.0          3.6           1.4          0.2  setosa

In [48]:
x=i[['Sepal.Length','Sepal.Width','Petal.Length','Petal.Width']]

In [49]:
y=i[['Species']]

In [51]:
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.3,stratify=y,random_state=100)

In [57]:
x_train.shape
x_test.shape

(45, 4)

In [66]:
dt=DecisionTreeClassifier(criterion='gini',random_state=100,max_depth=3,min_samples_leaf=5)

In [67]:
dt.fit(x_train,y_train)

DecisionTreeClassifier(max_depth=3, min_samples_leaf=5, random_state=100)

In [68]:
dt_pred=dt.predict(x_test)

In [69]:
con_dt=confusion_matrix(y_test,dt_pred)
con_dt

array([[15,  0,  0],
       [ 0, 15,  0],
       [ 0,  3, 12]], dtype=int64)

In [59]:
bagged=en.BaggingClassifier(base_estimator=None,n_estimators=50,oob_score=True)

In [62]:
bagged.fit(x_train,y_train)

C:\Users\hp\anaconda3\lib\site-packages\sklearn\utils\validation.py:73: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  return f(**kwargs)


BaggingClassifier(n_estimators=50, oob_score=True)

In [63]:
bag_pred=bagged.predict(x_test)

In [65]:
con_bag=confusion_matrix(y_test,bag_pred)
con_bag

array([[15,  0,  0],
       [ 0, 15,  0],
       [ 0,  3, 12]], dtype=int64)

In [70]:
adaBoost = en.AdaBoostClassifier()

In [71]:
adaBoost.fit(x_train,y_train)

C:\Users\hp\anaconda3\lib\site-packages\sklearn\utils\validation.py:73: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  return f(**kwargs)


AdaBoostClassifier()

In [72]:
boost_pred=adaBoost.predict(x_test)

In [73]:
con_boost=confusion_matrix(y_test,boost_pred)
con_boost

array([[15,  0,  0],
       [ 0, 15,  0],
       [ 0,  7,  8]], dtype=int64)

In [77]:
##Ada Boost 
(15+15+8)/45*100

84.44444444444444

In [78]:
randomForest = en.RandomForestClassifier(n_estimators=50, max_features=0.5, oob_score=True)

In [79]:
randomForest.fit(x_train,y_train)

<ipython-input-79-87f01160c5a2>:1: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  randomForest.fit(x_train,y_train)


RandomForestClassifier(max_features=0.5, n_estimators=50, oob_score=True)

In [80]:
RF_pred=randomForest.predict(x_test)

In [81]:
con_RF=confusion_matrix(y_test,RF_pred)
con_RF

array([[15,  0,  0],
       [ 0, 15,  0],
       [ 0,  3, 12]], dtype=int64)

# Diabetes Data

In [82]:
import os
os.getcwd()

'C:\\Users\\hp\\Desktop\\Python'

In [83]:
dia=pd.read_csv("diabetes.csv")

In [84]:
dia.shape

(768, 9)

In [85]:
dia.columns

Index(['Pregnancies', 'Glucose', 'BloodPressure', 'SkinThickness', 'Insulin',
       'BMI', 'DiabetesPedigreeFunction', 'Age', 'Outcome'],
      dtype='object')

In [86]:
dia.head()

Pregnancies  Glucose  BloodPressure  SkinThickness  Insulin   BMI  \
0            6      148             72             35        0  33.6   
1            1       85             66             29        0  26.6   
2            8      183             64              0        0  23.3   
3            1       89             66             23       94  28.1   
4            0      137             40             35      168  43.1   

   DiabetesPedigreeFunction  Age  Outcome  
0                     0.627   50        1  
1                     0.351   31        0  
2                     0.672   32        1  
3                     0.167   21        0  
4                     2.288   33        1

In [87]:
dia.isnull().sum()

Pregnancies                 0
Glucose                     0
BloodPressure               0
SkinThickness               0
Insulin                     0
BMI                         0
DiabetesPedigreeFunction    0
Age                         0
Outcome                     0
dtype: int64