1. Generate a random number between 1 and 9 (including 1 and 9). Ask the user to guess the number, then tell them whether they guessed too low, too high, or exactly right.
(Hint: remember to use the user input function)
Extras:
1. Keep the game going until the user types “exit”.
2. Keep track of how many guesses the user has taken, and when the game ends, print this out.

In [4]:
import random
count=0
while 1 :
    a=int(input('Guess a number between 1 and 9-->'))
    count+=1
    b=random.randint(1,9)
    if a==b:
        print("You Win!!")
    elif a>b:
        print("Too High")
    else:
        print("Too low")
    c=str(input("Do you want to continue: Press Y to Continue or EXIT to quit : "))
    if c=='Y':
        continue
    elif c=='EXIT':
        print('Your Number of Guesses =',count)
        break

Guess a number between 1 and 9-->4
Too low
Do you want to continue: Press Y to Continue or EXIT to quit : Y
Guess a number between 1 and 9-->3
Too low
Do you want to continue: Press Y to Continue or EXIT to quit : EXIT
Your Number of Guesses = 2


Print Number Pattern  : Double the number 
1
2 1
4 2 1 
8 4 2 1 
16 8 4 2 1
32 16 8 4 2 1


In [5]:
rows=6
for i in range(rows):
    for j in range(i):
        print(i,end='')
    print(" ")
        
    

 
1 
22 
333 
4444 
55555 


Reverse any number using While Loop.
Input - 431
Output - 134

In [7]:
a=int(input("Input a number"))
r=0
while a>0:
    rem=a%10
    r=r*10+rem
    a=a//10
print(r)
    

Input a number8651
1568


Sum of even numbers in fibonacci series upto the number selected by the user:
eg : if the user chooses 20 then the series will be : 1, 2, 3, 5, 8, 13 and the sum will be : 2 + 8


In [19]:
n=int(input('Enter the number of terms: '))
F0=0
f1=1
sum_even=0
for i in range(0,n):
    fib=F0+f1
    F0=f1
    f1=fib
    if fib%2==0:
        sum_even=sum_even+fib
print(sum_even)


Enter the number of terms: 10
44


Select the largest prime number present in the list. (Without using .sort() method)

In [15]:
num=int(input("Enter a Number: "))
for i in range(2,num):
    if num%i==0:
        print("Not Prime")
        break
else:
    print("Prime")

Enter a Number13
Prime


In [18]:
num=[3,4,5,7,12,13]
for x in num:
    for i in range(2,x):
        if x%i==0:
            print("%d is not a prime number"%x)
            break
    else:
        print("%d is  a prime number"%x)

3 is  a prime number
4 is not a prime number
5 is  a prime number
7 is  a prime number
12 is not a prime number
13 is  a prime number


nested loops

In [8]:
import numpy as np

In [9]:
lis=list(range(1,21))
no_rows=4
no_col=5
final_list=list()
for i in range(no_rows):
    row_list=list()
    for j in range(no_col):
        row_list.append(lis.pop(0))
    final_list.append(row_list)
print(np.array(final_list))

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]]


Co relation matrix from scratch